# Copyright (c) 2014 Rohan Chandra
# SPDX-License-Identifier: MIT
# The Jekyl theme "Type" used and modified under the above licence from https://github.com/rohanchandra/type-theme
#
# SITE CONFIGURATION
url: "0.0.0.0" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Hyperledger Grid
  gravatar: # Email MD5 hash
  description: "A project for building supply chain solutions" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Grid</h1>
  header_text_feature_image: ../examples/img/hero-bg.jpg
  footer_text: >
    <h2>Hyperledger Grid</h2>
    <p>
      <a href="http://www.linuxfoundation.org/privacy" target="_blank" title="Privacy Policy">Privacy Policy</a>
      &bull;
      <a href="http://www.linuxfoundation.org/terms" target="_blank" title="Terms of Service">Terms of Service</a>
    </p>
    <p>
      <small class="copyright">Copyright &copy; 2015-2019 contributors to Hyperledger Grid</small>
    </p>
  permalink: /:categories/:year/:month/:day/:release/:title/
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: hyperledger/grid
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: Hyperledger
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-135255838-1"
  disqus_shortname:
  katex: # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
# paginate: 5
# paginate_path: "info/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
keep_files: [./*]
source: ./source
