version: "2.1"

services:
  jekyll:
    image: sawtooth-jekyll:latest
    build:
      context: generator/
      dockerfile: ./Dockerfile
    working_dir: /srv/jekyll/
    command: bundle exec jekyll build -Vs ./source --config ./_config.yml
    volumes:
      - $PWD/generator:/srv/jekyll
  webserver:
    image: sawtooth-website
    container_name: sawtooth-website
    build:
      context: .
      dockerfile: webserver/Dockerfile
    expose:
      - 80
    ports:
      - 8000:80
    volumes:
      - $PWD/generator:/srv/jekyll